version: 1.0.{build}
skip_tags: true
os: Windows Server 2012 R2
before_build:
- git submodule update --init --recursive
- .\.nuget\nuget.exe restore
build:
  project: Microsoft.Web.Administration.sln
  verbosity: minimal